force-app/main/default/objects/OpportunityLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Dis_Value__c.field-meta.xml
<CustomField>
    <fullName>Dis_Value__c</fullName>
    <label>Dis_Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Disc_Type__c.field-meta.xml
<CustomField>
    <fullName>Disc_Type__c</fullName>
    <label>Disc Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amount</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/MSP__c.field-meta.xml
<CustomField>
    <fullName>MSP__c</fullName>
    <label>MSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Living Area</fullName>
            </value>
            <value>
                <fullName>Dining Area</fullName>
            </value>
            <value>
                <fullName>Family Lounge</fullName>
            </value>
            <value>
                <fullName>Bedroom</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Pantry</fullName>
            </value>
            <value>
                <fullName>Utility / Laundry</fullName>
            </value>
            <value>
                <fullName>Bathroom</fullName>
            </value>
            <value>
                <fullName>Common Washroom</fullName>
            </value>
            <value>
                <fullName>Ablution Area</fullName>
            </value>
            <value>
                <fullName>Passage / Corridor</fullName>
            </value>
            <value>
                <fullName>Staircase (Internal)</fullName>
            </value>
            <value>
                <fullName>Lobby / Entrance</fullName>
            </value>
            <value>
                <fullName>Balcony</fullName>
            </value>
            <value>
                <fullName>Porch / Sit-out</fullName>
            </value>
            <value>
                <fullName>Patio / Courtyard</fullName>
            </value>
            <value>
                <fullName>Roof</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Sloping Roof</fullName>
            </value>
            <value>
                <fullName>Building Exterior</fullName>
            </value>
            <value>
                <fullName>Facade / Elevation</fullName>
            </value>
            <value>
                <fullName>Staircase (External)</fullName>
            </value>
            <value>
                <fullName>Compound Wall</fullName>
            </value>
            <value>
                <fullName>Parking / Driveway</fullName>
            </value>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Retail / Showroom</fullName>
            </value>
            <value>
                <fullName>Restaurant / Cafe</fullName>
            </value>
            <value>
                <fullName>Hotel Lobby</fullName>
            </value>
            <value>
                <fullName>Commercial Washroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Dis_Value__c.field-meta.xml
<CustomField>
    <fullName>Dis_Value__c</fullName>
    <label>Discount Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Disc_Type__c.field-meta.xml
<CustomField>
    <fullName>Disc_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amount</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/MSP__c.field-meta.xml
<CustomField>
    <fullName>MSP__c</fullName>
    <label>MSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/OpportunityItemId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityItemId__c</fullName>
    <formula>OpportunityLineItem.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Item ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteLineItem_Handler.cls
public class QuoteLineItem_Handler {
//Update the oppo line items with quote fields
 /*   public static void afterInsertMethod(List<QuoteLineItem> newList) {
	System.debug('afterInsertMethod ');
        Map<Id, QuoteLineItem> qliByOliId = new Map<Id, QuoteLineItem>();
        for (QuoteLineItem qli : newList) {
            System.debug('qli.OpportunityItemId__c '+qli.OpportunityItemId__c);
            if (qli.OpportunityItemId__c != null) {
                qliByOliId.put(qli.OpportunityItemId__c, qli);
            }
        }

        if (qliByOliId.isEmpty()) return;

        List<OpportunityLineItem> olis = [
            SELECT Id, Area__c,MSP__c,Disc_Type__c
            FROM OpportunityLineItem
            WHERE Id IN :qliByOliId.keySet()
        ];
List<OpportunityLineItem> olist= new List<OpportunityLineItem>();
        for (OpportunityLineItem oli : olis) {
            QuoteLineItem qli = qliByOliId.get(oli.Id);
            oli.Area__c = qli.Area__c;
             oli.MSP__c = qli.MSP__c;
            oli.Disc_Type__c = qli.Disc_Type__c;
            oli.Dis_Value__c = qli.Dis_Value__c;
            olist.add(oli);
        }
  System.debug('.olist '+olist);
        if (!olist.isEmpty()) {
            update olist;
        }
    }*/
}