force-app/main/default/objects/Delivery_Group__c/Delivery_Group__c.object-meta.xml
<CustomObject>
    <label>Delivery Plan</label>
    <nameField>
        <displayFormat>DLV - {0000}</displayFormat>
        <label>Delivery Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Group__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Logistics Head Approved</fullName>
            </value>
            <value>
                <fullName>Logistics Head Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Group__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Group__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <formula>CASESAFEID( Sales_Order__r.QuoteId )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QuoteId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Group__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Delivery Plans</relationshipLabel>
    <relationshipName>Delivery_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Group__c/fields/Warehouse_Manager__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delivery_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Warehouse_Manager__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Checker Rejected</fullName>
            </value>
            <value>
                <fullName>Checker Approved</fullName>
            </value>
            <value>
                <fullName>Manager Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Stores information about warehouses for inventory management</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Warehouse_Manager__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Warehouses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeliveryPlanTriggerHandler.cls
Public class DeliveryPlanTriggerHandler {

    // Fetch Admin User ID
    private static Id adminId = [
        SELECT Id
        FROM User
        WHERE Profile.Name = 'System Administrator'
        AND IsActive = true
        LIMIT 1
    ].Id;

    // Fetch Notification Type
    private static CustomNotificationType dpType = [
        SELECT Id
        FROM CustomNotificationType
        WHERE DeveloperName = 'DeliveryPlan_Notification'
        LIMIT 1
    ];

    // Block Delivered status without approval
    public static void beforeUpdate( List<Delivery_Group__c> newList, Map<Id, Delivery_Group__c> oldMap) {
        for (Delivery_Group__c newDp : newList) {
            Delivery_Group__c oldDp = oldMap.get(newDp.Id);

            if (
                newDp.Delivery_Status__c == 'Delivered' &&
                oldDp.Delivery_Status__c != 'Delivered'
            ) {
                if (newDp.Approval_Status__c != 'Approved') {
                    newDp.addError(
                        'You cannot mark this Delivery Plan as Delivered until it is approved by the Warehouse Manager.'
                    );
                }
            }
        }
    }

    // Notify Admin when Delivery Plan is created
    public static void afterInsert(List<Delivery_Group__c> newPlans) {
        for (Delivery_Group__c dp : newPlans) {
            Messaging.CustomNotification noti =
                new Messaging.CustomNotification();

            noti.setTitle('Delivery Plan Created');
            noti.setBody(
                'A new Delivery Plan "' + dp.Name + '" has been created.'
            );
            noti.setNotificationTypeId(dpType.Id);
            noti.setTargetId(dp.Id);
            noti.send(new Set<String>{ adminId });
        }
    }

    // Notify Admin when Delivery Plan is marked Delivered
    public static void afterUpdate(List<Delivery_Group__c> newList, Map<Id, Delivery_Group__c> oldMap ) {
        for (Delivery_Group__c newDp : newList) {
            Delivery_Group__c oldDp = oldMap.get(newDp.Id);

            if (oldDp.Delivery_Status__c != 'Delivered' && newDp.Delivery_Status__c == 'Delivered' )
            {
                Messaging.CustomNotification noti = new Messaging.CustomNotification();

                noti.setTitle('Delivery Plan Delivered');
                noti.setBody(
                    'Delivery Plan "' + newDp.Name + '" has been marked as Delivered.'
                );
                noti.setNotificationTypeId(dpType.Id);
                noti.setTargetId(newDp.Id);
                noti.send(new Set<String>{ adminId });
            }
        }
    }

    // Populate Warehouse Manager based on Warehouse
    public static void populateWarehouseManager( List<Delivery_Group__c> newList,Map<Id, Delivery_Group__c> oldMap) {
        Set<Id> warehouseIds = new Set<Id>();

        for (Delivery_Group__c dp : newList) {
            if (
                dp.Warehouse__c != null &&
                (
                    oldMap == null ||
                    !oldMap.containsKey(dp.Id) ||
                    dp.Warehouse__c != oldMap.get(dp.Id).Warehouse__c
                )
            ) {
                warehouseIds.add(dp.Warehouse__c);
            }
        }

        if (warehouseIds.isEmpty()) return;

        Map<Id, Warehouse__c> warehouseMap =
            new Map<Id, Warehouse__c>([
                SELECT Id, Warehouse_Manager__c
                FROM Warehouse__c
                WHERE Id IN :warehouseIds
            ]);

        for (Delivery_Group__c dp : newList) {
            if (
                dp.Warehouse__c != null &&
                warehouseMap.containsKey(dp.Warehouse__c)
            ) {
                dp.Warehouse_Manager__c =
                    warehouseMap.get(dp.Warehouse__c).Warehouse_Manager__c;
            }
        }
    }
    

    // 🔹 Delivery Plan Created
    public static void onCreate(List<Delivery_Group__c> newOrders) {
        List<Delivery_Group__c> ordersWithQuote = new List<Delivery_Group__c>();

        for (Delivery_Group__c o : newOrders) {
            if (o.QuoteId__c != null) {
                ordersWithQuote.add(o);
            }
        }

        if (!ordersWithQuote.isEmpty()) {
            sendNotification(
                ordersWithQuote,
                'Delivery Plan Created from Salse Order',
                'A new Delivery Plan has been created from your quote.'
            );
        }
    }

    // 🔹 Order Approved / Rejected
    public static void onStatusChange(List<Delivery_Group__c> newList, Map<Id, Delivery_Group__c> oldMap) {
        List<Delivery_Group__c> approvedOrders = new List<Delivery_Group__c>();
        List<Delivery_Group__c> rejectedOrders = new List<Delivery_Group__c>();

        for (Delivery_Group__c o : newList) {
            Delivery_Group__c old = oldMap.get(o.Id);

            if (o.Approval_Status__c != old.Approval_Status__c && o.QuoteId__c != null) {
                if (o.Approval_Status__c == 'Activated') {
                    approvedOrders.add(o);
                } else if (o.Approval_Status__c == 'Rejected') {
                    rejectedOrders.add(o);
                }
            }
        }

        if (!approvedOrders.isEmpty()) {
            sendNotification(approvedOrders,'Delivery Plan Approved', 'Delivery Plan has been approved.');
        }

        if (!rejectedOrders.isEmpty()) {
            sendNotification(rejectedOrders,'Delivery Plan Rejected','Delivery Plan has been rejected.');
        }
    }

    // 🔹 Common Notification Method
    private static void sendNotification( List<Delivery_Group__c> orders, String title, String message) {
        // Collect Quote Ids
        Set<Id> quoteIds = new Set<Id>();
        for (Delivery_Group__c o : orders) {
            quoteIds.add(o.QuoteId__c);
        }

        // Get Quotes
        Map<Id, Quote> quoteMap = new Map<Id, Quote>(
            [SELECT Id, OwnerId FROM Quote WHERE Id IN :quoteIds]
        );


        for (Delivery_Group__c o : orders) {
            Quote q = quoteMap.get(o.QuoteId__c);
            if (q == null) continue;

            Messaging.CustomNotification notification =
                new Messaging.CustomNotification();

            notification.setTitle(title);
            notification.setBody(message + ' Order No: ' + o.Name);
            notification.setNotificationTypeId(dpType.Id);
            notification.setTargetId(o.Id);

            notification.send(new Set<String>{ q.OwnerId });
        }
    }
}